parameters:
  # Optional: dependencies of the job
  dependsOn: ''

  # Optional: A defined YAML pool - https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#pool
  pool:
    vmImage: vs2017-win2016

  CeapexPat: $(dn-bot-ceapex-package-r)
  GithubPat: $(BotAccount-dotnet-bot-repo-PAT)

jobs:
- job: OneLocBuild
  
  dependsOn: ${{ parameters.dependsOn }}

  displayName: OneLocBuild

  pool: ${{ parameters.pool }}

  variables:
    - group: OneLocBuildVariables

  steps:
    - task: Powershell@2
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/generate-locproject.ps1
      displayName: Generate LocProject.json

    - task: OneLocBuild@2
      displayName: OneLocBuild
      inputs:
        locProj: Localize/LocProject.json
        outDir: $(Build.ArtifactStagingDirectory)
        isCreatePrSelected: true
        repoType: gitHub
        gitHubPatVariable: "${{ parameters.GithubPat }}"
        packageSourceAuth: patAuth
        patVariable: ${{ parameters.CeapexPat }}
      continueOnError: true
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: Publish Localization Files
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/loc'
        PublishLocation: Container
        ArtifactName: Loc
      continueOnError: true
      condition: always()